radio:
	g++ -O3 -march=core2 ldpc.cpp decode.cpp encode.cpp itime.cpp mathfun.cpp main.cpp mtrand/mtrand.cpp mtrand/MTRand_gaussian.cpp

sprout:
	g++ -O3 -mcpu=ultrasparc -mtune=ultrasparc ldpc.cpp decode.cpp encode.cpp itime.cpp mathfun.cpp main.cpp mtrand/mtrand.cpp mtrand/MTRand_gaussian.cpp
